### ISSUE TITLE
Feature request: Configure GitHub action in workflow file

### ISSUE THREAD

**Issue by kantoniak** [fernandrone/linelint#4]
Hello @fernandrone, would it be possible to configure this action directly in workflow file?

**Comment by fernandrone** [comment]
Hi @kantoniak. Yes, and there's an example of this being used as a github action in this very repo: https://github.com/fernandrone/linelint/blob/master/.github/workflows/lint.yml. There's also some more information in the README.

Please let me know if this answers your question or if you run into any trouble 🙂

**Comment by kantoniak** [comment]
I mean moving flow options directly to a `yaml` in `.github/workflows/` folder, something like.
```
on: [push]
name: lint

jobs:
  linelint:
    runs-on: ubuntu-latest
    name: Check if all files end in newline
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Linelint
        uses: fernandrone/linelint@master
        id: linelint
        rules:
          end-of-file:
            enable: true
            disable-autofix: false
            single-new-line: true
```
It seems to be generally possible but not implemented for this action.

**Comment by fernandrone** [comment]
Oh, yeah, I got you now. You are correct, you can use this as an workflow but the individual options are not supported.

_However_ the workflow will *still* read the options from a `.linelint.yml` file at the root of your repository. So you can configure your options there. That's why I didn't make this feature a priority 👍🏻 would that help?

That said I do think it would be nice to be able to override some options through the workflow (just like you can override options as cli arguments) so I'd be inclined to accept any PRs adding support for this 🙂

Also I have some free time for the next couple weeks thst I'd like to invest in this project although I'm not sure this is the topmost priority (since the `.linelint.yml` config should work for many use cases)

**Comment by fernandrone** [comment]
Hey @kantoniak I've decided to take a quick look at this and I'm not sure it's possible with this syntax:

```yaml
      - name: Linelint
        uses: fernandrone/linelint@master
        id: linelint
        rules:
          end-of-file:
            enable: true
            disable-autofix: false
            single-new-line: true
```

I don't have a lot of experience with github actions but checking the docs, to pass parameters you need to use the `with` syntax, see https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepswith

```yaml
jobs:
  my_first_job:
    steps:
      - name: My first step
        uses: actions/hello_world@main
        with:
          first_name: Mona
          middle_name: The
          last_name: Octocat
```

![image](https://user-images.githubusercontent.com/7269710/95636159-c6029f00-0a64-11eb-96ac-378a9dd4ed83.png)

The thing with this is that there is only a single level of configuration, so it would be very hard to map the complex configuration required for the linter. Maybe if we prefix it with something like this:

```yaml
      - name: Linelint
        uses: fernandrone/linelint@master
        id: linelint
        with:
          eof-enable: true
          eof-disable-autofix:
          eof-single-new-line: true
```

Where `eof` is obviously short for `end-of-file`. But this can get very complex really fast and I don't see much advantage in just setting up a configuration file at the root of the repo and read from there, like this https://github.com/fernandrone/linelint/blob/master/.linelint.yml

Maybe at most add a single parameter to allow for a different file, like:

```yaml
      - name: Linelint
        uses: fernandrone/linelint@master
        id: linelint
        with:
          config: ./.github/workflow-linelint.yml
```

This way the user is not forced to use the default `.linelint.yml` file at the root of the repo for their github action.

How does that sound?
